apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-adapter
    targetRevision: 4.10.0
    helm:
      values: |
        prometheus:
          url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local
          port: 9090

        rules:
          default: false
          custom:
            - seriesQuery: 'http_requests_total{namespace!="",pod!=""}'
              resources:
                overrides:
                  namespace:
                    resource: namespace
                  pod:
                    resource: pod
              name:
                matches: "^(.*)_total"
                as: "${1}"
              metricsQuery: >
                sum(rate(http_requests_total{<<.LabelMatchers>>}[1m]))
                by (namespace, pod)

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
