apiVersion: apps/v1
kind: Deployment
metadata:
  name: booktrack-backendapp
  namespace: booktrack
  labels:
    app.kubernetes.io/name: booktrack
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booktrack-backendapp
  template:
    metadata:
      name: booktrack-backendapp
      labels:
        app: booktrack-backendapp
    spec:
      serviceAccount: backend-sa
      containers:
      - name: booktrack-backendapp
        image: mniranjanr7/booktrack-backend:f2b0c53ba4a1d5184a6fc604517cc9df9e38bbbf
        envFrom:
        - configMapRef:
            name: postgre-config
        - secretRef:
            name: postgre-login
        ports:
        - name: http-port
          containerPort: 8000
        startupProbe:
          httpGet:
            path: /startup
            port: 8000
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "250Mi"
