apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: booktrack-backend-hpa
  namespace: booktrack
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: booktrack-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
