apiVersion: v1
kind: Service
metadata:
  name: svc-booktrack-backend-green
  namespace: booktrack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: booktrack
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: green
  ports:
  - port: 8000
    targetPort: 8000
