apiVersion: v1
kind: Service
metadata:
  name: svc-postgresql
  namespace: booktrack
spec:
  selector:
    app.kubernetes.io/name: booktrack
    app.kubernetes.io/component: database
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
