apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-booktrack
provisioner: linodebs.csi.linode.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true