apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-booktrack-backend-preview
  namespace: booktrack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: booktrack.example.com
    http:
      paths:
      - path: /api-preview
        pathType: Prefix
        backend:
          service:
            name: svc-booktrack-backend-green
            port:
              number: 8000
