apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-booktrack-frontend
  namespace: booktrack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: booktrack.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-booktrack-frontend
            port:
              number: 80
      # Backend FastApi
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: svc-backend
            port:
              number: 8000
